### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by dltmdrbtjd** [matty255/wordplay_public#1]
- 프로젝트 끝내시느라 고생 많으셨습니다. 😎 

- 새로고침시에 데이터를 불러오는건 해결을 하신것 같아보이네요? 사이트에서 현재 잘 동작하고 있는걸로 보입니다. 아직 서버와 데이터를 주고받는 과정이 익숙하지 않으셔서 그럴거에요. 그리고 firebase를 사용해서 serverless로 개발을 하고 계시기 때문에 사실상 백엔드와 프론트엔드를 모두 동시에 하고 계신것과 같습니다. 그래서 더 혼란이 있을수있죠 너무 크게 걱정하지 않으셔도 됩니다 ! 점점 더 잘해지실거니까요.
- 현재 시점에서는 새로고침으로 생긴 문제들은 모두 해결하신걸로 보이네요.. 사이트에서는 전부 잘 작동하네요 ! 고생 많으셨습니다 ㅎㅎ 데이터를 주고 받는 과정이 아직 익숙하지 않아서 어려움이 많이 생길수도 있습니다. 그래서 어떤 식으로 서버와 데이터를 주고받게 되는지를 한 번 혼자 글로써도 좋고 그려봐도 좋고 정리해보시고 개발을 해보시면 더 이해가 쉬울겁니다.
- 결과적으로 스스로 다 문제를 해결하신것 같군요 ! 멋지십니다 고생 많으셨어요 😄

**Comment by matty255** [comment]
와 감사합니다!!! 넵 맞아여, 팀과제를 하다보니까 해결되어서 수정하려고 했는데 새로내기만 가능하더라구여ㅠㅠ
글이나 그림으로 정리해보기! 서버리스 메모! 😄 열심히 해보겠습니다!
